
site_name: OpenFLUID community
theme:
  name : readthedocs
  custom_dir: theme_readthedocs_custom
extra_css:
  - css/custom.css
  - css/cookieconsent.min.css
extra_javascript:
  - js/cookieconsent.min.js
  - js/cookie-banner.js

site_url: http://127.0.0.1:8000
repo_url: https://github.com/OpenFLUID/openfluid-community-docs
edit_uri: blob/master/src/docs

extra:
  production: False
  ofweb_url: http://127.0.0.1:1313/
  twitter_account: "@OpenFLUID"
  image_og : "ofcommunity_og.png"

google_analytics: ['UA-10058595-1', 'openfluid-project.org']

copyright: 'Copyright INRA-Montpellier SupAgro - <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a>'
site_favicon: img/favicon.png

markdown_extensions:
  - admonition
  - pymdownx.tasklist
  - toc:
      permalink: True
  - markdown_include.include:
      base_path: docs

plugins:
  - markdownextradata: {}

pages:
  - Getting started :
    - Installation : 'start/install.md'
    - Manuals : 'start/manuals.md'
    - Training sessions : 'start/trainings.md'
    - Charter : 'start/charter.md'
    - Support : 'start/support.md'
  - General information :
    - Used terms and acronyms: 'general/terms.md'
    - FAQ : 'general/faq.md'
    - License : 'general/license.md'
    - References : 'general/references.md'
    - Releases notes : 'general/changelog.md'
    - Versions numbers : 'general/versionsnum.md'
    - Logo, icon and more: 'general/logoicon.md'
    - Misc. ressources : 'general/miscress.md'
  - Simulators development :
    - Development environment : 'scidev/scidevenv.md'
    - Create and build a simulator : 'scidev/simbuild.md'
    - Conventions for naming simulators and data : 'scidev/simdatanaming.md'
    - Coding style : 'scidev/codestyle.md'
    - Good practices for simulators development : 'scidev/simgood.md'
    - Simulators documentation : 'scidev/simdoc.md'
    - Requirements for simulators release : 'scidev/simrelease.md'
    - Updating the source code of simulators : 'scidev/simupdate.md'
  - OpenFLUID and R :
    - ROpenFLUID package : 'external/ropenfluid.md'
    - Example of simulation analyses : 'external/ranalysis.md'
  - Platform development :
    - Development environment : 'coredev/devenv.md'
    - Building from sources : 'coredev/build.md'
    - Coding style : 'coredev/codestyle.md'
    - Working with source code : 'coredev/srccodework.md'
    - Good practices for commits : 'coredev/commitsgood.md'
    - Process for OpenFLUID releases : 'coredev/releasepcs.md'
    - FluidHub API : 'coredev/fluidhub.md'
    - Bugs and feature requests : 'coredev/issues.md'
  - Notes about models :
    - WaresHub repository : 'models/wareshub.md'
    - MHYDAS : 'models/mhydas.md'
